@api = http://localhost:5000/api/auth

POST {{api}}/signup 
content-type: application/json

{  
 "username": "username1", 
 "email": "carla1@gmail.com",  
"password": "password6"
}


###
POST {{api}}/signin

###
GET {{api}}/profile

###
GET {{api}}/videos/62696addb675fdbf73fa7a99

###
POST {{api}}/videos HTTP/1.1
content-type: application/json

{
   "url": "https://youtu.be/stBc8AfMkjcd",
   "title": "Title Test video",
    "description": "this is a test video"
}

###
DELETE {{api}}/videos/626962e54ac5d582f08f1cbd

###
PUT {{api}}/videos/62696addb675fdbf73fa7a99 HTTP/1.1
Content-Type: application/json

{
    "title": "updated title"
}