@api = http://localhost:5000/api/auth

POST {{api}}/signup HTTP/1.1
content-type: application/json

{  
 "username": "username4", 
 "email": "carlammh110@gmail.com",  
"password": "password"
}

###
POST {{api}}/signin
content-type: application/json

{  
 "email": "carlammh110@gmail.com",  
"password": "password"
}

###
GET {{api}}/profile
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcwMWRkZjkxNWE2NDFiYjVmMjVmYTciLCJpYXQiOjE2NTE1MjUzNDcsImV4cCI6MTY1MTYxMTc0N30.1HBurnvh9Urnf74RT0cJKLYOje46K155Hr46GaxeSyc

###
GET {{api}}/videos

###
POST {{api}}/videos HTTP/1.1
content-type: application/json

{
   "url": "https://youtu.be/stBc8AfMkjcd",
   "title": "Title Test video",
    "description": "this is a test video"
}

###
DELETE {{api}}/videos/626962e54ac5d582f08f1cbd

###
PUT {{api}}/videos/627009d38d16370574452e5c HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcwMWRkZjkxNWE2NDFiYjVmMjVmYTciLCJpYXQiOjE2NTE1MjUzNDcsImV4cCI6MTY1MTYxMTc0N30.1HBurnvh9Urnf74RT0cJKLYOje46K155Hr46GaxeSyc
Content-Type: application/json

{
    "title": "new updated room management 2"
}